namespace HLWanted_TownMex
{
array<string> g_Sounds =
{
	"wanted/townmex/ahhh.wav",
	"wanted/townmex/argh.wav",
	"wanted/townmex/arghhhh.wav",
	"wanted/townmex/askmigeal.wav",
	"wanted/townmex/askoldman.wav",
	"wanted/townmex/askpadre.wav",
	"wanted/townmex/ayee.wav",
	"wanted/townmex/badday.wav",
	"wanted/townmex/badmen.wav",
	"wanted/townmex/baityou.wav",
	"wanted/townmex/banditsaway.wav",
	"wanted/townmex/beansandcorn.wav",
	"wanted/townmex/believeso.wav",
	"wanted/townmex/blackday.wav",
	"wanted/townmex/boresmetodeath.wav",
	"wanted/townmex/buzzard.wav",
	"wanted/townmex/cactus.wav",
	"wanted/townmex/cantgoon.wav",
	"wanted/townmex/chafe.wav",
	"wanted/townmex/changemind.wav",
	"wanted/townmex/comehelpus.wav",
	"wanted/townmex/crazymad.wav",
	"wanted/townmex/cursevillage.wav",
	"wanted/townmex/cutout.wav",
	"wanted/townmex/deadfear.wav",
	"wanted/townmex/donthurtme.wav",
	"wanted/townmex/doyouneverstop.wav",
	"wanted/townmex/drinkthis.wav",
	"wanted/townmex/dullpain.wav",
	"wanted/townmex/eek.wav",
	"wanted/townmex/enoughbullets.wav",
	"wanted/townmex/evilmen.wav",
	"wanted/townmex/fertiliser.wav",
	"wanted/townmex/fightlastnight.wav",
	"wanted/townmex/findburo.wav",
	"wanted/townmex/goldinteeth.wav",
	"wanted/townmex/gonemad.wav",
	"wanted/townmex/greko.wav",
	"wanted/townmex/gringo.wav",
	"wanted/townmex/hearrustling.wav",
	"wanted/townmex/hearsomething.wav",
	"wanted/townmex/hearthat.wav",
	"wanted/townmex/helllo.wav",
	"wanted/townmex/hello.wav",
	"wanted/townmex/helpme.wav",
	"wanted/townmex/helpus.wav",
	"wanted/townmex/heyamigo.wav",
	"wanted/townmex/holiday.wav",
	"wanted/townmex/hottoday.wav",
	"wanted/townmex/howpossible.wav",
	"wanted/townmex/ifitoldyou.wav",
	"wanted/townmex/iforgot.wav",
	"wanted/townmex/ifyousayso.wav",
	"wanted/townmex/iknownothing.wav",
	"wanted/townmex/illfollowyou.wav",
	"wanted/townmex/imshot.wav",
	"wanted/townmex/inthisworld.wav",
	"wanted/townmex/ithinkso.wav",
	"wanted/townmex/iwish.wav",
	"wanted/townmex/laterhuh.wav",
	"wanted/townmex/letsbegoing.wav",
	"wanted/townmex/lookfunny.wav",
	"wanted/townmex/lunchtoday.wav",
	"wanted/townmex/madcrazy.wav",
	"wanted/townmex/madman.wav",
	"wanted/townmex/mariasmustache.wav",
	"wanted/townmex/mistake.wav",
	"wanted/townmex/mnogo.wav",
	"wanted/townmex/moreguns.wav",
	"wanted/townmex/mrsherriffsir.wav",
	"wanted/townmex/mygoodfriend.wav",
	"wanted/townmex/needsome.wav",
	"wanted/townmex/newbeans.wav",
	"wanted/townmex/newspaper.wav",
	"wanted/townmex/no.wav",
	"wanted/townmex/noburo.wav",
	"wanted/townmex/nogood.wav",
	"wanted/townmex/noicant.wav",
	"wanted/townmex/noo.wav",
	"wanted/townmex/nowait.wav",
	"wanted/townmex/ofcourse.wav",
	"wanted/townmex/oherrrr.wav",
	"wanted/townmex/ohhahh.wav",
	"wanted/townmex/ohhh.wav",
	"wanted/townmex/ohno.wav",
	"wanted/townmex/ok.wav",
	"wanted/townmex/onlyachicken.wav",
	"wanted/townmex/onlycamefor.wav",
	"wanted/townmex/opengate.wav",
	"wanted/townmex/pain1.wav",
	"wanted/townmex/pain2.wav",
	"wanted/townmex/pain3.wav",
	"wanted/townmex/pain4.wav",
	"wanted/townmex/pain5.wav",
	"wanted/townmex/pleasesenior.wav",
	"wanted/townmex/prayyouknow.wav",
	"wanted/townmex/resthere.wav",
	"wanted/townmex/ridenburo.wav",
	"wanted/townmex/runoutoftown.wav",
	"wanted/townmex/rusure.wav",
	"wanted/townmex/santamaria.wav",
	"wanted/townmex/seensombrero.wav",
	"wanted/townmex/sherriff.wav",
	"wanted/townmex/sherriffintown.wav",
	"wanted/townmex/shout.wav",
	"wanted/townmex/si.wav",
	"wanted/townmex/siesta.wav",
	"wanted/townmex/siestatime.wav",
	"wanted/townmex/signore.wav",
	"wanted/townmex/simplefarmers.wav",
	"wanted/townmex/simplepeasant.wav",
	"wanted/townmex/slowingudown.wav",
	"wanted/townmex/smallhat.wav",
	"wanted/townmex/squeeeeek.wav",
	"wanted/townmex/stainsout.wav",
	"wanted/townmex/stareat.wav",
	"wanted/townmex/stench.wav",
	"wanted/townmex/stitchwound.wav",
	"wanted/townmex/sure.wav",
	"wanted/townmex/talktomuch.wav",
	"wanted/townmex/tendhorses.wav",
	"wanted/townmex/teqilaonyou.wav",
	"wanted/townmex/terriblesmell.wav",
	"wanted/townmex/thathurt.wav",
	"wanted/townmex/thinkitstrue.wav",
	"wanted/townmex/tireofspeak.wav",
	"wanted/townmex/todangerous.wav",
	"wanted/townmex/ugh.wav",
	"wanted/townmex/untrue.wav",
	"wanted/townmex/useashot.wav",
	"wanted/townmex/waitforothers.wav",
	"wanted/townmex/wastebullets.wav",
	"wanted/townmex/weakback.wav",
	"wanted/townmex/wearefarmers.wav",
	"wanted/townmex/whatdoyoumean.wav",
	"wanted/townmex/whattheywant.wav",
	"wanted/townmex/whatthink.wav",
	"wanted/townmex/whatyoudo.wav",
	"wanted/townmex/whitewash.wav",
	"wanted/townmex/whydothis.wav",
	"wanted/townmex/whynot.wav",
	"wanted/townmex/wifekillme.wav",
	"wanted/townmex/worriedwife.wav",
	"wanted/townmex/wyatterp.wav",
	"wanted/townmex/yeowww.wav",
	"wanted/townmex/yes.wav",
	"wanted/townmex/yess.wav",
	"wanted/townmex/youarecrazy.wav",
	"wanted/townmex/youareshot.wav",
	"wanted/townmex/youbadday.wav",
	"wanted/townmex/youlookhurt.wav",
	"wanted/townmex/youngboys.wav",
	"wanted/townmex/youngones.wav"
};

void Precache()
{
	g_Game.PrecacheModel( "models/wanted/townmex.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex01.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex02.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex03.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex04.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex05.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex06.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmex07.mdl" );
	g_Game.PrecacheGeneric( "models/wanted/townmext.mdl" );

	for( uint uiIndex = 0; uiIndex < g_Sounds.length(); ++uiIndex )
	{
		g_SoundSystem.PrecacheSound( g_Sounds[uiIndex] ); // cache
		g_Game.PrecacheGeneric( "sound/" + g_Sounds[uiIndex] ); // client has to download
	}
}

} // end of HLWanted_TownMex namespace